version: '2'
volumes:
  partons-mysql-data:
    driver: local

services:
  mysql:
    build:
      context: .
      dockerfile: .docker/Dockerfile.mysql
    restart: 'no'
    volumes:
      - "partons-mysql-data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: 'partons'
      MYSQL_USER: 'partons'
      MYSQL_PASSWORD: 'partons'

  shell:
    build:
      context: .
      dockerfile: .docker/Dockerfile.partons
    restart: 'no'
    depends_on:
      - mysql
    volumes:
      - ".:/root/workspace/partons-example"
    command: /bin/bash

  compile:
    build:
      context: .
      dockerfile: .docker/Dockerfile.partons
    restart: 'no'
    volumes:
      - ".:/root/workspace/partons-example"
      - ".docker/scripts:/root/scripts"
    command: /bin/bash /root/scripts/compile_example.sh

  partons:
    build:
      context: .
      dockerfile: .docker/Dockerfile.partons
    depends_on:
      - mysql
    restart: 'no'
    volumes:
      - ".:/root/workspace/partons-example"
      - ".docker/scripts:/root/scripts"
